-- 코드를 입력하세요
SELECT info.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(review.REVIEW_SCORE), 2) as SCORE
FROM REST_INFO info
JOIN REST_REVIEW review ON info.REST_ID = review.REST_ID
WHERE info.ADDRESS LIKE '서울%'
GROUP BY info.REST_ID, info.REST_NAME, info.FOOD_TYPE, info.FAVORITES, info.ADDRESS
ORDER BY SCORE DESC, info.FAVORITES DESC